# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/cus_payment.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
from datetime import datetime

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap
from pypromptpay import qr_code

from ucwblib import GetDatabase, ICON_PATH


class Ui_frm_cus_payment(object):

    def __init__(self, amount=0):
        self.amount = amount

    def setupUi(self, frm_cus_payment):
        frm_cus_payment.setObjectName("frm_cus_payment")
        # frm_cus_payment.resize(375, 480)
        # frm_cus_payment.setMinimumSize(QtCore.QSize(375, 480))
        # frm_cus_payment.setMaximumSize(QtCore.QSize(375, 480))
        frm_cus_payment.setFixedSize(QtCore.QSize(375, 480))

        frm_cus_payment.setWindowFlags(QtCore.Qt.WindowCloseButtonHint)

        # Set window icon
        frm_cus_payment.setWindowIcon(QtGui.QIcon(ICON_PATH))

        self.lbl_qrcode = QtWidgets.QLabel(frm_cus_payment)
        self.lbl_qrcode.setGeometry(QtCore.QRect(90, 100, 200, 200))
        font = QtGui.QFont()
        font.setFamily("Kanit")
        font.setPointSize(12)
        self.lbl_qrcode.setFont(font)
        self.lbl_qrcode.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_qrcode.setObjectName("lbl_qrcode")
        self.verticalLayoutWidget = QtWidgets.QWidget(frm_cus_payment)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 310, 371, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_accname = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Kanit")
        font.setPointSize(12)
        self.lbl_accname.setFont(font)
        self.lbl_accname.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_accname.setObjectName("lbl_accname")
        self.verticalLayout.addWidget(self.lbl_accname)
        self.lbl_accno = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Kanit")
        font.setPointSize(12)
        self.lbl_accno.setFont(font)
        self.lbl_accno.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_accno.setObjectName("lbl_accno")
        self.verticalLayout.addWidget(self.lbl_accno)
        self.lbl_amount = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Kanit")
        font.setPointSize(14)
        self.lbl_amount.setFont(font)
        self.lbl_amount.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_amount.setObjectName("lbl_amount")
        self.verticalLayout.addWidget(self.lbl_amount)
        self.frame_header = QtWidgets.QFrame(frm_cus_payment)
        self.frame_header.setGeometry(QtCore.QRect(0, 0, 381, 91))
        self.frame_header.setStyleSheet("background-color: rgb(0, 148, 217);")
        self.frame_header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_header.setObjectName("frame_header")
        self.lbl_title = QtWidgets.QLabel(self.frame_header)
        self.lbl_title.setGeometry(QtCore.QRect(0, 10, 371, 71))
        font = QtGui.QFont()
        font.setFamily("Kanit")
        font.setPointSize(16)
        self.lbl_title.setFont(font)
        self.lbl_title.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_title.setObjectName("lbl_title")
        self.horizontalLayoutWidget = QtWidgets.QWidget(frm_cus_payment)
        # self.horizontalLayoutWidget.setGeometry(QtCore.QRect(70, 430, 241, 39))
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(118, 430, 140, 39))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        # self.btn_cancel = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        # sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.btn_cancel.sizePolicy().hasHeightForWidth())
        # self.btn_cancel.setSizePolicy(sizePolicy)
        # font = QtGui.QFont()
        # font.setFamily("Kanit")
        # font.setPointSize(14)
        # self.btn_cancel.setFont(font)
        # self.btn_cancel.setObjectName("btn_cancel")
        # self.horizontalLayout.addWidget(self.btn_cancel)
        self.btn_confirm = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Kanit")
        font.setPointSize(14)
        self.btn_confirm.setFont(font)
        self.btn_confirm.setStyleSheet("background:rgb(255, 124, 10);\n"
                                       "color: rgb(255, 255, 255);")
        self.btn_confirm.setObjectName("btn_confirm")
        self.horizontalLayout.addWidget(self.btn_confirm)
        self.frame_header.raise_()
        self.lbl_qrcode.raise_()
        self.verticalLayoutWidget.raise_()
        self.horizontalLayoutWidget.raise_()

        self.retranslateUi(frm_cus_payment)
        QtCore.QMetaObject.connectSlotsByName(frm_cus_payment)

        self.loadQR()

        # Event-Driven
        self.btn_confirm.clicked.connect(self.confirm)
        # self.btn_cancel.clicked.connect(self.cancel)

    def loadQR(self):
        with GetDatabase() as conn:
            db = conn.get_database('ucwb')
            condition = {'name': 'payment_detail'}
            cursor = db.settings.find(condition)

            acc_name = cursor[0]['value']['acc_name']
            acc_no = cursor[0]['value']['acc_no']
            amount = self.amount

            self.lbl_accname.setText("ชื่อบัญชี : {}".format(acc_name))
            self.lbl_accno.setText("เลขบัญชี : {}".format(acc_no))
            self.lbl_amount.setText("จำนวน : {:,.2f} บาท".format(amount))

            # Check if 'temp' folder exists
            path = "temp"
            if not os.path.exists(path):
                os.makedirs(path)

            current_time = str(datetime.now().replace(microsecond=0)).replace(':', '-')
            qr_path = "temp/qr_{}.png".format(current_time)
            # Creating PromptPay QR Code
            qr_code(acc_no.replace('-', ''),
                    one_time=True, path_qr_code=qr_path, country="TH", money=str(amount), currency="THB")

            pixmap = QPixmap(qr_path)
            pixmap = pixmap.scaled(self.lbl_qrcode.width(), self.lbl_qrcode.height())
            self.lbl_qrcode.setPixmap(pixmap)

    def confirm(self):
        frm_cus_payment.hide()

    def setAmount(self, amount):
        self.amount = amount

    # def cancel(self):
    #     frm_cus_payment.hide()

    def retranslateUi(self, frm_cus_payment):
        _translate = QtCore.QCoreApplication.translate
        frm_cus_payment.setWindowTitle(_translate("frm_cus_payment", "UCWB - Payment"))
        self.lbl_qrcode.setText(_translate("frm_cus_payment", "QR Code"))
        self.lbl_accname.setText(_translate("frm_cus_payment", "ชื่อบัญชี : xxxx xxxx"))
        self.lbl_accno.setText(_translate("frm_cus_payment", "No. : xxx-xxx-xxxx"))
        self.lbl_amount.setText(_translate("frm_cus_payment", "จำนวน : 0.00 บาท"))
        self.lbl_title.setText(_translate("frm_cus_payment", "กรุณาชำระเงิน\n"
                                                             "PromptPay"))
        # self.btn_cancel.setText(_translate("frm_cus_payment", "ยกเลิก"))
        self.btn_confirm.setText(_translate("frm_cus_payment", "ยืนยัน"))


frm_cus_payment = None
if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    frm_cus_payment = QtWidgets.QDialog()
    ui = Ui_frm_cus_payment()
    ui.setupUi(frm_cus_payment)
    frm_cus_payment.show()
    sys.exit(app.exec_())
