# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/cus_uploadslip.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frm_cus_uploadslip(object):
    def setupUi(self, frm_cus_uploadslip):
        frm_cus_uploadslip.setObjectName("frm_cus_uploadslip")
        frm_cus_uploadslip.resize(375, 480)
        frm_cus_uploadslip.setMinimumSize(QtCore.QSize(375, 450))
        frm_cus_uploadslip.setMaximumSize(QtCore.QSize(375, 480))

        frm_cus_uploadslip.setWindowFlags(QtCore.Qt.WindowCloseButtonHint)
        # frm_cus_uploadslip.setFixedSize(QtCore.QSize(900, 600))

        self.lbl_qrcode = QtWidgets.QLabel(frm_cus_uploadslip)
        self.lbl_qrcode.setGeometry(QtCore.QRect(30, 100, 321, 301))
        font = QtGui.QFont()
        font.setFamily("Kanit")
        font.setPointSize(16)
        self.lbl_qrcode.setFont(font)
        self.lbl_qrcode.setStyleSheet("")
        self.lbl_qrcode.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_qrcode.setObjectName("lbl_qrcode")
        self.frame_header = QtWidgets.QFrame(frm_cus_uploadslip)
        self.frame_header.setGeometry(QtCore.QRect(0, 0, 381, 91))
        self.frame_header.setStyleSheet("background-color: rgb(0, 148, 217);")
        self.frame_header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_header.setObjectName("frame_header")
        self.lbl_title = QtWidgets.QLabel(self.frame_header)
        self.lbl_title.setGeometry(QtCore.QRect(0, 10, 371, 71))
        font = QtGui.QFont()
        font.setFamily("Kanit")
        font.setPointSize(16)
        self.lbl_title.setFont(font)
        self.lbl_title.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_title.setObjectName("lbl_title")
        self.horizontalLayoutWidget = QtWidgets.QWidget(frm_cus_uploadslip)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(70, 420, 241, 39))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_cancel = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_cancel.sizePolicy().hasHeightForWidth())
        self.btn_cancel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Kanit")
        font.setPointSize(14)
        self.btn_cancel.setFont(font)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout.addWidget(self.btn_cancel)
        self.btn_confirm = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Kanit")
        font.setPointSize(14)
        self.btn_confirm.setFont(font)
        self.btn_confirm.setStyleSheet("background:rgb(255, 124, 10);\n"
                                       "color: rgb(255, 255, 255);")
        self.btn_confirm.setObjectName("btn_confirm")
        self.horizontalLayout.addWidget(self.btn_confirm)
        self.frame_header.raise_()
        self.lbl_qrcode.raise_()
        self.horizontalLayoutWidget.raise_()

        self.retranslateUi(frm_cus_uploadslip)
        QtCore.QMetaObject.connectSlotsByName(frm_cus_uploadslip)

    def retranslateUi(self, frm_cus_uploadslip):
        _translate = QtCore.QCoreApplication.translate
        frm_cus_uploadslip.setWindowTitle(_translate("frm_cus_uploadslip", "UCWB - Payment Proof"))
        self.lbl_qrcode.setText(_translate("frm_cus_uploadslip", "Drag and Drop\n"
                                                                 "ไฟล์รูปภาพสลิปโอนเงิน\n"
                                                                 "(jpg/png)"))
        self.lbl_title.setText(_translate("frm_cus_uploadslip", "กรุณาอัปโหลด\n"
                                                                "หลักฐานการชำระเงิน"))
        self.btn_cancel.setText(_translate("frm_cus_uploadslip", "ยกเลิก"))
        self.btn_confirm.setText(_translate("frm_cus_uploadslip", "ยืนยัน"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    frm_cus_uploadslip = QtWidgets.QDialog()
    ui = Ui_frm_cus_uploadslip()
    ui.setupUi(frm_cus_uploadslip)
    frm_cus_uploadslip.show()
    sys.exit(app.exec_())
else:
    import sys

    app = QtWidgets.QApplication(sys.argv)
    frm_cus_uploadslip = QtWidgets.QDialog()
    ui = Ui_frm_cus_uploadslip()
    ui.setupUi(frm_cus_uploadslip)
